import {React, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Sider from './../components/Sider';
import Mainscreen from './../components/MainScreen/Mainscreen';
import {AiOutlineSearch, AiOutlinePlus} from 'react-icons/ai'
import { siderBtn } from './../utils/siderBtn';
import Button from './../components/common/Button';
import Toggle from './../components/common/Toggle';



const EventTypes = () => {

  const [featureArrow, setFeatureArrow] = useState(0)
  //const [popularArrow, setPopularArrow] = useState(0)
  //const [showCategory, setShowCategory] = useState(0)

  function featureLeft() {
    if (featureArrow > 0) {
      setFeatureArrow(featureArrow - 1)
    }
  }

  function featureRight(){
    if (featureArrow < featureInfo.length-5) {
      setFeatureArrow(featureArrow + 1)
    }
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex bg-white w-full">
     <Sider>

     
    <div>
    <div className="w-10/12 mx-auto justify-between flex mb-[50px]">
        <img 
        className="w-[74px] aspect-auto"
            src="https://app.cal.com/calcom-logo-white-word.svg"
            alt="cal.com"
        />
 <AiOutlineSearch
          fontSize={20}
         />
    </div>


    {
        siderBtn.map((item) => (
            <Button 
                icon={item.icon}
                text={item.text}
                link={item.href}
            />
        ))
    }
    </div>


    <div className="rounded-md border-[1px] mt-[38px] mx-auto border-gray w-[160px] p-1">
          <h1 className="text-sm text-center font-semibold py-2 mx-auto">
          Dynamic booking links
          </h1>

          <h1 className="text-xs text-darkgray mx-auto w-11/12">
          Booking link that allows people to quickly ...
          </h1>

          <video className="w-11/12 rounded-md my-2 mx-auto" controls
          src="https://www.youtube.com/watch?v=60HJt8DOVNo"
          />

          <div className="text-xs w-11/12 mx-auto">
            Learn more
          </div>


      </div>

     </Sider>

     {/* MAIN SCREEN  */}
     <div
    className="w-full max-w-[1000px] ml-[227px] mx-auto px-[48px] pt-[40px]"
    >

        <div className="flex justify-between">
            <div className="flex flex-col">
              <h1
              className="text-[1.25rem] font-bold text-darkblue"
              >Event Types</h1>
              <h1
              className="text-btntextgray text-[0.875rem]"
              >Create events to share for people to book on your calendar.</h1>
            </div>

            <button className="bg-[#292929] hover:bg-[#696969] rounded-md w-[82px] h-[36px] my-auto flex justify-evenly">
                <AiOutlinePlus 
                fontSize={15}
                className="my-auto text-white text-[0.875rem]"
                />
                <span className="my-auto text-white text-[0.875rem]">New</span>
            </button>

        </div>

        <div className="w-full h-fit my-[30px]">
        <div className="border-[1px] border-lightgrayBg w-full rounded-t-md flex justify-between py-[15px] px-[23px]">
             
             <div className="flex justify-between">
                 
                <div>
                   <div className="flex w-[685px]">
                     <div className="text-[0.875rem] font-[700]">
                     30 Min Meeting
                     </div>

                     <div className="font-[400] text-[0.75rem] text-[#6B7280] my-auto p-1">
                      /teenfounders/30min
                     </div>
                   </div>

                   <div>
                      <div className="flex rounded-md bg-[#F3F4F6] text-[0.75rem] font-[500] w-fit px-2 py-1">
                        <img 
                        className="w-[14px] h-[14px] my-auto mr-1"
                        src="clock.svg"
                        />
                        30m
                      </div>
                   </div>
                </div>


                <div className="flex justify-between">
                    <div className="my-auto mx-2">
                  <Toggle/>
                  </div>

                  <div className="mx-2 my-auto">
                    <button className="border-[1px] rounded-l-md border-lightgrayBg p-2 ">
                      <img 
                      className="w-[16px] h-[16px]"
                      src="preview.svg"
                      />
                    </button>

                    <button className="border-[1px] border-l-none border-lightgrayBg p-2">
                    <img 
                      className="w-[16px] h-[16px]"
                      src="appLink.svg"
                      />
                    </button>  
                    
                    <button className="border-[1px] rounded-r-md border-lightgrayBg p-2">
                    <img 
                      className="w-[16px] h-[16px]"
                      src="more.svg"
                      />
                    </button>
                  </div>
                </div>

             </div>  
        </div>


        <div className="border-[1px] border-lightgrayBg w-full flex justify-between py-[15px] px-[23px]">
             
             <div className="flex justify-between">
                 
                <div>
                   <div className="flex w-[685px]">
                     <div className="text-[0.875rem] font-[700]">
                     15 Min Meeting
                     </div>

                     <div className="font-[400] text-[0.75rem] text-[#6B7280] my-auto p-1">
                      /teenfounders/15min
                     </div>
                   </div>

                   <div>
                      <div className="flex rounded-md bg-[#F3F4F6] text-[0.75rem] font-[500] w-fit px-2 py-1">
                        <img 
                        className="w-[14px] h-[14px] my-auto mr-1"
                        src="clock.svg"
                        />
                        15m
                      </div>
                   </div>
                </div>


                <div className="flex justify-between">
                    <div className="my-auto mx-2">
                  <Toggle/> 
                  </div>

                  <div className="mx-2 my-auto">
                    <button className="border-[1px] rounded-l-md border-lightgrayBg p-2 ">
                      <img 
                      className="w-[16px] h-[16px]"
                      src="preview.svg"
                      />
                    </button>

                    <button className="border-[1px] border-l-none border-lightgrayBg p-2">
                    <img 
                      className="w-[16px] h-[16px]"
                      src="appLink.svg"
                      />
                    </button>  
                    
                    <button className="border-[1px] rounded-r-md border-lightgrayBg p-2">
                    <img 
                      className="w-[16px] h-[16px]"
                      src="more.svg"
                      />
                    </button>
                  </div>
                </div>

             </div>
             </div>

             <div className="border-[1px] border-lightgrayBg w-full rounded-b-md flex justify-between py-[15px] px-[23px]">
             
             <div className="flex justify-between">
                 
                <div>
                   <div className="flex w-[685px]">
                     <div className="text-[0.875rem] font-[700]">
                     Secret Meeting
                     </div>

                     <div className="font-[400] text-[0.75rem] text-[#6B7280] my-auto p-1">
                     /teenfounders/secret
                     </div>
                   </div>

                   <div>
                      <div className="flex rounded-md bg-[#F3F4F6] text-[0.75rem] font-[500] w-fit px-2 py-1">
                        <img 
                        className="w-[14px] h-[14px] my-auto mr-1"
                        src="clock.svg"
                        />
                        15m
                      </div>
                   </div>
                </div>


                <div className="flex justify-between">
                    <div className="my-auto mx-2">
                  <Toggle/>
                  </div>

                  <div className="mx-2 my-auto">
                    <button className="border-[1px] rounded-l-md border-lightgrayBg p-2 ">
                      <img 
                      className="w-[16px] h-[16px]"
                      src="preview.svg"
                      />
                    </button>

                    <button className="border-[1px] border-l-none border-lightgrayBg p-2">
                    <img 
                      className="w-[16px] h-[16px]"
                      src="appLink.svg"
                      />
                    </button>  
                    
                    <button className="border-[1px] rounded-r-md border-lightgrayBg p-2">
                    <img 
                      className="w-[16px] h-[16px]"
                      src="more.svg"
                      />
                    </button>
                  </div>
                </div>

             </div>
             </div>



        </div>


    </div>
      </main>
    </>
  )
}

export default EventTypes