import Head from 'next/head'
import {useState} from 'react'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { app } from './../utils/app';
import AppCard from './../components/appCard';
import SearchBar from './../components/searchbar';
import Featured from './../components/featured';
import { featureInfo } from './../utils/feature';
import PopularCard from './../components/popularCard';
import{AiOutlineArrowLeft, AiOutlineArrowRight} from 'react-icons/ai'
import { category } from './../utils/categories';
import Sider from './../components/sider';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [featureArrow, setFeatureArrow] = useState(0)
  const [popularArrow, setPopularArrow] = useState(0)
  const [showCategory, setShowCategory] = useState(0)

  function featureLeft() {
    if (featureArrow > 0) {
      setFeatureArrow(featureArrow - 1)
    }
  }

  function featureRight(){
    if (featureArrow < featureInfo.length-5) {
      setFeatureArrow(featureArrow + 1)
    }
  }

  function popularLeft() {
    if (popularArrow > 0) {
      setPopularArrow(popularArrow - 1)
    }
  }

  function popularRight() {
    if (popularArrow < app.length-3) {
      setPopularArrow(popularArrow + 1)
    }
  }

  function categoryLeft() {
    if (showCategory > 0) {
      setShowCategory(showCategory - 1)
    }
  }

  function categoryRight() {
    if (showCategory < category.length - 7) {
      setShowCategory(showCategory + 1)
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-auto max-h-fit min-h-screen flex">
     
     {/* <div className="">

     </div> */}
      <div className="w-[230px] h-screen min-h-fit bg-red">
         <Sider/>
      </div>

      <div className="max-w-[950px]">

      
      <div className="flex justify-between w-11/12 max-w-[1200px] mx-auto py-10">
        <div className="flex flex-col">
          <div className="text-[20px] font-bold">
             App Store
          </div>
          <div className="text-darkgray py-1">
          Connecting people, technology and the workplace.
          </div>
        </div>
        <SearchBar/>
      </div>
      
      <div className="w-11/12 text-[17px] flex font-semibold justify-between mx-auto pb-6 pt-2">
        <span>Featured Categories</span>

        <div className="flex">
        <div className="hover:bg-gray rounded-md p-2 w-[40px]">
           <AiOutlineArrowLeft
            onClick={()=> {featureLeft()}}
            fontSize={15} className="mx-auto my-auto cursor-pointer"
           />
           </div>
           <div className="hover:bg-gray rounded-md p-2 w-[40px]">
           <AiOutlineArrowRight
            onClick={()=> {featureRight()}}
            fontSize={15} className="mx-auto my-auto cursor-pointer"
           />
           </div>
        </div>

      </div>
      <div className="w-11/12 flex overflow-x-scroll scroll-pl-6 snap-x scroll-auto no-scrollbar mx-auto">
      {
       
          featureInfo.slice(featureArrow, featureArrow + 9).map((item) => (
        <Featured
        key={item.title}
          title={item.title}
          featureNo={item.featureNo}
        />
      ))
      
      }
      </div>
    

      <div className="w-11/12 text-[17px] flex font-semibold justify-between mx-auto pb-6 pt-2">
        <span>Most Popular</span>

        <div className="flex">
        <div className="hover:bg-gray rounded-md p-2 w-[40px]">
           <AiOutlineArrowLeft
          onClick={()=> {popularLeft()}}
            fontSize={15} className="mx-auto my-auto cursor-pointer"
           />
           </div>
           <div className="hover:bg-gray rounded-md p-2 w-[40px]">
           <AiOutlineArrowRight
          onClick={()=> {popularRight()}}
            fontSize={15} className="mx-auto my-auto cursor-pointer"
           />
           </div>
        </div>

      </div>

      <div className="w-11/12 flex overflow-x-scroll mb-8 scroll-pl-6 snap-x hover:scroll-auto scroll-smooth no-scrollbar mx-auto">
      {
       
       app.slice(popularArrow, popularArrow + 9).map((item) => (
     <PopularCard
     key={item.name}
       logo={item.logo} title={item.name} desc={item.desc}
     />
   ))
   
   }
   </div>

   <div className="w-11/12 text-[17px] flex font-semibold justify-between mx-auto pb-6 pt-2">
        <span>All Apps</span>

        <div className="flex relative">
        <AiOutlineArrowLeft
        onClick={() => {categoryLeft()}}
          className={`my-auto absolute top-2 ${(showCategory === 0) ? 'opacity-0' : 'opacity-100'}`}
        />
       {category.slice(showCategory, showCategory + 7).map((item) => (
        <div 
        key={item.title}
        className="rounded-md p-3 py-2 text-[14px] max-w-fit mx-1 hover:bg-[#111827] hover:text-white bg-lightgray">
          {item.title}
         </div>
       ))
         }
         <AiOutlineArrowRight
         onClick={() => {categoryRight()}}
          className={`my-auto absolute right-0 top-2 ${(showCategory === category.length-7) ? 'opacity-0' : 'opacity-100'}`}
         />
        </div>

      </div>
        <div className="grid grid-cols-4 mx-auto w-11/12">
            {
              app.map((item) => (
              <AppCard 
              key={item.name}
              logo={item.logo} title={item.name} desc={item.desc} />
            ))
            }
        </div>
        </div>
      </main>
    </>
  )
}
