import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from './../components/Navbar';
import Landing from './../components/Landing';
import Mobile from './../components/Mobile';
import Download from './../components/Download';
import Footer from './../components/Footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen bg-white min-h-screen ">
        
        <Navbar/>
        <Landing/>
        <Mobile/>
        <Download/>
        <Footer/>

      </div>
    </>
  )
}
