export const featureInfo = [
    {title: "Payment",
    featureNo: 8,
    },
    {title: "Web3",
    featureNo: 12,
    },
    {title: "Video",
    featureNo: 21,
    },
    {title: "Other",
    featureNo: 89,
    },
    {title: "Calendar",
    featureNo: 34,
    },
    {title: "Automation",
    featureNo: 32,
    },
    {title: "Analytics",
    featureNo: 17,
    },
    {title: "Games",
    featureNo: 12,
    },
    {title: "Business",
    featureNo: 79,
    },
    {title: "Other",
    featureNo: 89,
    },
    {title: "Calendar",
    featureNo: 34,
    },
    {title: "Automation",
    featureNo: 32,
    },
    {title: "Analytics",
    featureNo: 17,
    },
    {title: "Games",
    featureNo: 12,
    },
    {title: "Business",
    featureNo: 79,
    },

]