import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import QueryCard from './../components/queryCard';
import Form from './../components/form';
import Profile from './../components/profile';
import QuesImg from './../components/quesImg';
import Vote from './../components/vote';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@100&family=Poppins:wght@300&display=swap" rel="stylesheet"/>
      </Head>
      <main className="bg-white max-h-fit py-12 align-middle">
        <QueryCard/>

        <Form/>

        <Profile/>

        {/* proofs folder */}
        <QuesImg/>

        <Vote/>
      </main>
    </>
  )
}
